name: makhosi_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^7.1.1
  permission_handler: ^5.0.1+1
  provider: ^4.3.2+3
  page_transition: ^1.1.5
  cached_network_image: ^2.0.0
  objectdb: ^1.0.7+1
  share: ^0.6.4+3
  flutter_html: ^0.11.1
  http: ^0.12.1
  pin_code_fields: ^3.0.0
  shared_preferences: ^0.5.12+4
  image_picker: ^0.6.7+10
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.0
  firebase_auth: ^0.18.0+1
  google_maps_flutter: ^0.5.33
  location: ^3.0.0
  geocoder: ^0.2.1
  google_sign_in: ^4.5.4
  bubble_tab_indicator: ^0.1.4
  rating_bar: ^0.2.0
  table_calendar: ^2.2.3
  agora_rtc_engine: ^3.1.3
  webview_flutter: ^1.0.7
  language_pickers: ^0.2.0+1
  firebase_dynamic_links: ^0.6.3
  flutter_mailer: ^1.0.0
  flutter_launcher_icons: ^0.8.1
  flutter_country_picker: ^0.1.6
  #permission_handler: ^5.0.0+hotfix.10
  charts_flutter: ^0.9.0
  font_awesome_flutter: ^8.10.0
  curved_navigation_bar: ^0.3.2
  percent_indicator: "^2.1.7+2"
  hexcolor: ^0.0.1
  firebase_core: ^0.5.0
  braintree_payment: ^1.2.4
  slide_to_act: ^0.1.3+1
  audioplayers: ^0.16.2
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^3.0.2
  intl: ^0.16.1
  rxdart: ^0.25.0
  weather: ^1.2.4
  flutter_inappwebview: ^4.0.0+4
  flutter_open_whatsapp: ^0.1.2
  #flutter_linkedin: ^1.0.2
  #flutter_facebook_login: ^3.0.0
  clay_containers: ^0.2.2
  rating_dialog: ^1.0.0
  carousel_pro: ^1.0.0
  tabbar: ^0.1.1
  bottom_navy_bar: ^5.5.0

  screenshot: ^0.2.0
  photo_view: ^0.10.2
  modal_progress_hud: ^0.1.3
  flutter_email_sender: ^4.0.0
  esys_flutter_share: ^1.0.2



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
#  intl: ^0.17.0-nullsafety.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/iconlauncher.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - images/
    - assets/map_style.txt
    - assets/images/
    - images/administration_images/
    - images/ic_back.png
    - images/ic_folder.png
    - images/ic_popmenu.png
    - images/ic_search.png
    - images/ic_users.png
    - images/ic_folder_colored.png
    - images/ic_filter.png
    - images/ic_return.png
    - images/storage_icon.png
    - images/circleavater.png
    - images/ic_support.png
    - images/go_backbtn.png
    - images/ic_file.png
    - images/ic_chat.png
    - images/ic_calendar.png
    - images/ic_delete.png
    - assets/audio/pickup-ringing.mp3
    - assets/audio/phone-busy.mp3
    - assets/audio/call-ring.mp3


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins_light.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 400
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Thin.ttf


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
